services:
  - type: web
    name: my-telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: 8717837657:AAEnqE3FLn7K018PKZuwBq3wSNaFfMJiYPE
        sync: false